name: workfolw dispatch manually
on:
  workflow_dispatch:
    inputs:
      environments:
        description: 'The environment to deploy to'
        required: true
        type: environment
      notify:
        description: 'Notify of Deployment?'
        required: true
        type: boolean
        default: false
        
jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
      - run: echo "Deploying to ${{ github.event.inputs.environments}} environments"
    notify:
     runs-on: ubuntu-latest
     if: ${{ github.event.inputs.notify }}
     steps:
      - run: echo "Deploy to ${{ github.event.inputs.environment }}"
                    
        
        
    
