name: use the secret
on: ['push']
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: "use secret in a script"
        run: echo "The secret value is $MY_SECRET"
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}


    

      
