name: workflow dispatch 
on:
 workflow_dispatch:
    inputs:
      environments:
          discription: 'The environment to deploy to'
          required: true
          type: environment
          
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to ${{ github.event.inputs.environments }} environment"

